In [2]:
import mysql.connector as conn

In [3]:
mydb=conn.connect(host='localhost',user='root',passwd="Madhu911734")

In [4]:
mydb

In [5]:
cursor = mydb.cursor()

In [6]:
cursor.execute("show databases")

In [7]:
cursor.fetchall()

[('1st_day_on_SQL',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('pysqldb',),
 ('Shivam',),
 ('SQLlearner',),
 ('sys',)]

In [ ]:
cursor.execute("create database pysqldb")

In [12]:
cursor.execute("create table pysqldb.kk(studentid INT(10), firstname VARCHAR(30), lastname VARCHAR(30), rigid INT(30), classname VARCHAR(30)  )")

In [24]:
cursor.execute('use pysqldb')

In [ ]:
#cursor.execute('show table')

In [ ]:
#cursor.fetchall()

[]

In [27]:
cursor.execute('SHOW TABLES')
for table in cursor:
    print(table)

('kk',)

In [29]:
cursor.execute("insert into pysqldb.kk values(45,'kishan','mg',34,'fsds')")

In [30]:
mydb.commit()

In [31]:
cursor.execute('select * from pysqldb.kk')

In [32]:
cursor.fetchall()

[(45, 'kishan', 'mg', 34, 'fsds')]

In [13]:
ls

In [ ]:
import csv
with open('glass.data', 'r') as f:
    glass_data = csv.reader(f, delimiter='\n')
    for i in glass_data:
        print(i[0])

FileNotFoundError: [Errno 2] No such file or directory: 'glass.data'

In [ ]:
cursor.execute('create table pysqldb.glassdata(col1 INT(10) ,col2 float(10,5),col3 float(10,5) ,col4 float(10,5) , col5 float(10,5),col6 float(10,5) ,clo7 float(10,5) , col8 float(10,5) , col9 float(10,5) , col10 float(10,5) , col11 INT(10)) ')

In [ ]:
cursor.execute('insert into pysqldb.glassdata values(1,1.234,3.234,24.32,5.432,49.231,6.321,87.34,95.309,102.76,0.08)')

In [20]:
cursor.execute('insert into pysqldb.glassdata values(1,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.00,1)')

In [22]:
mydb.commit()

In [23]:
with open('glass.data','r') as f:
    glass_data=csv.reader(f,delimiter='\n')
    for i in glass_data:
        print(type(i[0]))
        print(f'insert into glassdata values ({str(i[0])})')
        cursor.execute('insert into pysqldb.glassdata values({values})'.format(values = ((i[0]))))

FileNotFoundError: [Errno 2] No such file or directory: 'glass.data'

In [24]:
mydb.commit()

In [25]:
cursor.execute('select * from pysqldb.glassdata ')

In [26]:
cursor.fetchall()

[(1, 1.234, 3.234, 24.32, 5.432, 49.231, 6.321, 87.34, 95.309, 102.76, 0.08),
 (1, 1.52101, 13.64, 4.49, 1.1, 71.78, 0.06, 8.75, 0.0, 0.0, 1.0)]

In [27]:
import pandas as pd

In [28]:
pd.read_sql('select * from pysqldb.glassdata ',mydb)

/var/folders/br/l24p9wqx0ml2rhgy4bgyvl9w0000gn/T/ipykernel_36683/2613805430.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select * from pysqldb.glassdata ',mydb)

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11
0,1,1.23400,3.234,24.32,5.432,49.231,6.321,87.34,95.309,102.76,0.08
1,1,1.52101,13.640,4.49,1.100,71.780,0.060,8.75,0.000,0.00,1.00

In [29]:
pd.read_sql('show databases ',mydb)

/var/folders/br/l24p9wqx0ml2rhgy4bgyvl9w0000gn/T/ipykernel_36683/2236643307.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('show databases ',mydb)

             Database
0      1st_day_on_SQL
1  information_schema
2               mysql
3  performance_schema
4             pysqldb
5              Shivam
6          SQLlearner
7                 sys